name: CI Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install nextflow
      run: sudo bash; mkdir /opt/nextflow; cd /opt/nextflow; wget https://github.com/nextflow-io/nextflow/releases/download/v21.04.3/nextflow; chmod +x nextflow;
    - name: Add nextflow to path
      run: echo "/opt/nextflow" >> $GITHUB_PATH;
    - name: Install nf-test
      run: sudo bash; mkdir /opt/nf-test; cd /opt/nf-test; wget https://github.com/askimed/nf-test/releases/download/v0.3.0/nf-test-0.3.0.tar.gz; tar xvfz nf-test-0.3.0.tar.gz; chmod +x nf-test;
    - name: Add nf-test to path
      run: echo "/opt/nf-test" >> $GITHUB_PATH;
    - name: Run nf-test tests
      run:  nf-test test
    - name: Run static Tests
      run:  ./run-tests.sh
